services:
  database:
    container_name: guardai-database
    image: postgres:16-alpine
    volumes:
      - ./data:/var/lib/postgresql/data
    networks:
      - application
    ports:
      - "5432:5432"

    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=guardai
      - TZ=America/Sao_Paulo

networks:
  application:
    driver: bridge
