services:
  database:
    container_name: guardai-database
    image: postgres:16-alpine
    volumes:
      - ./data:/var/lib/postgresql/data
    networks:
      - application
    ports:
      - "5432:5432"

    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=guardai
      - TZ=America/Sao_Paulo

  backend:
    image: node:20.18.0-alpine
    container_name: guardai-backend
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - application
    ports:
      - "3000:3000"
    depends_on:
      - database

networks:
  application:
    driver: bridge
